// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXZWeyVMizHvG-PzkKDh7m9ZPZNGFIjQA',
    appId: '1:625844249402:android:5e72bdd797596f6343a603',
    messagingSenderId: '625844249402',
    projectId: 'site-8f4b1',
    storageBucket: 'site-8f4b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ewLV8CZJ_eLmRSEbpNEHr0XTI0AKvok',
    appId: '1:625844249402:ios:69d28cea76993cb943a603',
    messagingSenderId: '625844249402',
    projectId: 'site-8f4b1',
    storageBucket: 'site-8f4b1.firebasestorage.app',
    iosBundleId: 'com.site.siteApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAo9RM9Y-KmRCWW4ieUmtM3FAUAuKSa60U",
    authDomain: "site-8f4b1.firebaseapp.com",
    projectId: "site-8f4b1",
    storageBucket: "site-8f4b1.firebasestorage.app",
    messagingSenderId: "625844249402",
    appId: "1:625844249402:web:2e538ca74552726f43a603"
    );

}